### ISSUE TITLE
No foreign key on payment schema???

### ISSUE THREAD

**Issue by BackgroundBoy** [2110423-2019-2/sec2_Krapaomookrob#12]
Is foreign key missing or does it not need here?
![image](https://user-images.githubusercontent.com/42508009/74331567-8ba60c80-4dc6-11ea-9969-6d2d4ab9e625.png)

**Comment by tirogen** [comment]
adding row
`$table->foreign('user_id')->references('id')->on('courses');`

**Comment by tirogen** [comment]
adding row
`$table->foreign('user_id')->references('id')->on('users');`

**Comment by BackgroundBoy** [comment]
@Wiwan5  don't forget to update the schema file
