### ISSUE TITLE
Should we create student_courses table?

### ISSUE THREAD

**Issue by taan02991** [2110423-2019-2/sec2_Krapaomookrob#22]
I think we need to have student_courses table that contains id, userId, courseId, status to keep track that the student enroll which course and status when student cancel the course. So what do you think?

**Comment by tirogen** [comment]
whatever you see fit

**Comment by tirogen** [comment]
whatever you think is best

**Comment by BackgroundBoy** [comment]
Good idea!

**Comment by tongplw** [comment]
let's create the table, it is the main point of this matching project
the status should include payment status also
