### ISSUE TITLE
Problem using Vue js

### ISSUE THREAD

**Issue by BackgroundBoy** [2110423-2019-2/sec2_Krapaomookrob#7]
My vue component is not showing, mix.js work though. 

this is my app.js:
![image](https://user-images.githubusercontent.com/42508009/74106934-b3665c00-4b9d-11ea-91f9-973000a3eee7.png)

and this is my vue component:
 
![image](https://user-images.githubusercontent.com/42508009/74106949-ef012600-4b9d-11ea-9390-45cdad6b22a9.png)

**Comment by tirogen** [comment]
try `npm run dev` or `npm run watch`
don't hesitate to ask me if isn't work

**Comment by BackgroundBoy** [comment]
try both, not working

**Comment by tirogen** [comment]
which branch are you doing? i want to see your code

**Comment by BackgroundBoy** [comment]
Branch Pinn but i haven't commit the code that have js.

**Comment by tirogen** [comment]
commit  diiwaa

**Comment by tirogen** [comment]
i found solutions
1. adding `<div id="app">` covers component
2. adding `app.js` in layout blade template
